version: "3.8"

services:
  front_admin:
    image: node:16-alpine
    working_dir: /src
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src

    command: sh -c "npm install && npm run dev"
